### ISSUE TITLE
[Bug] Can't delete triggers

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#1]
Selecting remove on a trigger does not remove it from the list.

**Comment by hankinsoft** [comment]
For triggers/alias/notes, they won't get removed until you hit accept. When you hit the remove, they get a strikethrough as shown in the following video:

![CleanShot 2023-01-14 at 11 33 23](https://user-images.githubusercontent.com/3160528/212480014-364a5e1a-dca0-452a-a023-4298ba6ea68d.gif)

Then once you hit accept, anything marked for deletion should be removed. Is this what you are seeing? Or are they not being removed when you hit accept?

**Comment by dak** [comment]
That worked. The strikethrough was so subtle I couldn't see it until you mentioned it.
