### ISSUE TITLE
[Bug] Data Folder inaccessible

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#14]
Opening the data folder opens the iCloud Drive, but the data folder itself is not visible. Connections within the data folder can also be found using search, but attempting to open them or their enclosing folder either opens iCloud Drive or leads to a perpetual loop of opening the same folder.

**Comment by hankinsoft** [comment]
Unfortunately, I can't do anything about this one. Finder mucks with iCloud drive data folders. What I have been doing is using terminal to access the folder structure when needed. I'm hoping Apple resolves this in a future macOS update.
