### ISSUE TITLE
[Bug] Awkward Subscription Name

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#16]
Name shows up as a URI instead of the name of the app like every other subscription, both for the top line app name, and for the sub line with the subscription type.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1371232/211663200-28bcb3b9-3f64-45cf-be6d-4298970b9b77.png">

**Comment by hankinsoft** [comment]
Thanks for the note. I've got a change for this submitted. I can't remembver if it needs a new app version to be sumitted as well, but if I notice it changes I will confirm.

**Comment by dak** [comment]
Confirmed fixed.
