### ISSUE TITLE
[Bug] Delay with Subscription

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#17]
I'm still getting the opening delay despite having an active subscription.

**Comment by hankinsoft** [comment]
Hmmm. Just to check if you close the app completely and re-open it you are still seeing the delay? Doing some investigating to see if I can reproduce.

**Comment by dak** [comment]
Yes, I tried restarting the app to see if that resolved it during testing and I'm still getting the delay. I'm using a different connection than the default one as well.

**Comment by dak** [comment]
Latest release fixes this issue.
