### ISSUE TITLE
Connections periodically don't display

### ISSUE THREAD

**Issue by issimojay** [hankinsoft/MudClient#27]
I used to be able to simply create a new connection and the others would then be found and appear, however, today I've done so and they are just gone.

I gather that they are in the icloud folder but can't be seen as I've found them in the past with search.

It would be really appreciated if we could set the location of these files as well because I get very long lag times clicking to change aliases etc, presumably because it's syncing from icloud.

<img width="935" alt="Screenshot 2024-04-04 at 10 12 54 pm" src="https://github.com/hankinsoft/MudClient/assets/60369760/98754a55-0a7e-4cd7-98d0-f07404ebfe93">

Thank you for developing it and doing updates, though!

**Comment by issimojay** [comment]
Just an update as a bit of a clue, when they disappear if I restart my computer they will display again when I open it up.

Macbook Pro 16 Inch 2021, M1 Max, 64GB, Sonoma 14.3

**Comment by hankinsoft** [comment]
Hmmmm, interesting, I've never seen this before. If possible could you upload your log file when you see this? You can find it by going to 'View' -> 'Logs'.

**Comment by hankinsoft** [comment]
> It would be really appreciated if we could set the location of these files as well because I get very long lag times clicking to change aliases etc, presumably because it's syncing from iCloud.

I'll take a look at setting this for a future build. It's a good idea.

**Comment by issimojay** [comment]
Yep definitely will.

If it's a hint, another major issue almost certainily related is that every time I click 'alias' to change the aliases or triggers I get the beachball of death / pinwheel of death and it completely freezes up for about a minute.

Here's the logs. I just did one at the end so you could see.

I'd say it's very likely related to the same issue, they are being stored on the icloud drive which is doing weird things (like downloading it from scratch every time perhaps?)

[com.hankinsoft.app.mudclient 2024-04-14--11-11-01-622.log](https://github.com/hankinsoft/MudClient/files/14972570/com.hankinsoft.app.mudclient.2024-04-14--11-11-01-622.log)

**Comment by issimojay** [comment]
Okay happened again!

Here's the logs and screenshots.

<img width="937" alt="image" src="https://github.com/hankinsoft/MudClient/assets/60369760/a1903534-a893-4946-b652-8e498e7089b8">

<img width="666" alt="image" src="https://github.com/hankinsoft/MudClient/assets/60369760/bc1f746b-cfe3-4b9e-b697-95f45e59dd59">

[com.hankinsoft.app.mudclient 2024-04-16--11-24-18-828.log](https://github.com/hankinsoft/MudClient/files/14996077/com.hankinsoft.app.mudclient.2024-04-16--11-24-18-828.log)

**Comment by issimojay** [comment]
And log file after a restart
[com.hankinsoft.app.mudclient 2024-04-16--11-24-18-828.log](https://github.com/hankinsoft/MudClient/files/14996151/com.hankinsoft.app.mudclient.2024-04-16--11-24-18-828.log)

**Comment by issimojay** [comment]
Hi guys, just checking in to let you know that this issue has resolved either through an update or by itself with the OS. May have had something to do with icloud.
