### ISSUE TITLE
[Bug] Show Trigger in Finder Crashes app

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#3]
When selecting `Show in Finder` on a trigger, the app crashes every time.

**Comment by hankinsoft** [comment]
The crash is fixed for the next build, although it has the same finder looping issue as #14 as they are stored in iCloud drive. I've made the log file log out the path when you do a 'show in finder' and added a 'View' -> 'Logs' menu item which shows the log file which can be used to find the actual path. At this moment terminal is a better way to navigate the files.

**Comment by dak** [comment]
Confirmed fixed.
