### ISSUE TITLE
[Feature] MCCP

### ISSUE THREAD

**Issue by dak** [hankinsoft/MudClient#5]
Support Mud Client Compression Protocol: https://mudhalla.net/tintin/protocols/mccp/

**Comment by hankinsoft** [comment]
For #5, #6, #7, #8 and #9 is there a specific one you're looking to have that would be useful to you now? I feel like these are probably something fewer users would use, so I plan on adding them as I get more requests for them, but if one would help you out now, please let me know.

**Comment by dak** [comment]
#7 would be the most value for the effort as it's a fairly simple protocol, although you'd want to expose it as variables for scripting too.
#6 is probably the most complex to implement but would be the most valuable.
#5 is fairly minimal in value but implementation should just be integrating zlib.

#9 is pretty much superfluous/obsoleted by #7, so that could honestly be ignored. #8 is lower on the list as well.

**Comment by hankinsoft** [comment]
MCCP is enabled for the next build. I'll be looking into #7 shortly as well. I'll post here once the build is available.

**Comment by dak** [comment]
> MCCP is enabled for the next build. I'll be looking into #7 shortly as well. I'll post here once the build is available.

How's that build coming?

**Comment by hankinsoft** [comment]
Sorry, my bad. I lost focus. I'll try to get that build with MCCP released this week. It will not yet have #7 though (I've been able to get GMCP messaging, but haven't setup triggering for it yet).

**Comment by hankinsoft** [comment]
Build 2023.10 should now be available. You can enable MCCP2 either when editing the connection (use the 'Advanced' -> 'Enable MCCP2' checkmark) or during a connection run the command '#enableMCCP2'.

**Comment by dak** [comment]
Awesome. Confirmed this is working now!
